name: 'Resource translator'
description: 'A GitHub action that uses Azure Cognitive Services Translator to generate .resx resource files given a source .resx file.'
branding:
  icon: flag
  color: gray-dark
inputs:
  subscriptionKey:
    description: 'The Azure Cognitive Services translator resource subscription key.'
    required: true
  endpoint:
    description: 'The Azure Cognitive Services translator resource endpoint.'
    required: true
  region:
    description: 'The Azure Cognitive Services translator resource region. This is optional when using a global translator resource.'
    required: false
  sourceLocale:
    description: 'The source locale (for example, ''en'') used to create the glob pattern for which resource (**/*.en.resx) files to use as input.'
    required: false
  toLocales:
    description: 'Optional locales to translate to, otherwise all possible locals are targeted. Example input, "es,de,fr" or ["es","de","fr"]. Requires double quotes.'
    required: false
outputs:
  summary-title:
    description: 'The summary details as a title, for example: "Machine-translated 320 files, a total of 5,418 translations"'
  summary-message:
    description: 'GitHub flavored markdown translation summary, with details of the resulting translations.'
  has-new-translations:
    description: 'A boolean value, indicating whether or not new translations exist as a result of running this action.'
runs:
  using: 'node12'
  main: 'dist/resource-translator/index.js'