name: build

on:
  push:
    branches: [ main ]
    paths-ignore: 
    - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm i
      - run: npm run build
      - run: npm run test
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3.4.1
        with:
          title: 'Latest dist build'
          body: 'Automated build to ensure latest bits are distributed.'
